### PR TITLE
Binary

### PR DESCRIPTION
**Pull request by Haleyo**

### CODE REVIEW

**Comment by Haleyo** [comment]
@lewisc @blbarker @dmsuehir 
Please review and sign off on this

**Comment by Haleyo** [comment]
Please sign off on this

**Comment by Haleyo** [comment]
Note to self: fix recall and precision, f_measure calculations. 

To everyone else, I messed up the checking of recall, precision, etc., it passes but I need to tweak it. It is a small change. Once the code review is complete I will edit this as well.

**Comment by dmsuehir** [comment]
:100:

**Pull request merged**
